---
title: "Case-control estimation: Worm's eye"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEnry{Case-control estimation: Worm's eye}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

First install the package from source if not already installed.

```{r, eval =FALSE}
devtools::install_github("cjbarrie/extremeR")

library(extremeR)
```

We then load the package into memory as follows.

```{r, warning = F, message = F}
library(extremeR)
library(dplyr)
```

We can  then load the data we need into memory using the data bundled in this package as follows. 

```{r}
data(survey_egypt)
data(shape_egypt)
data(denom_mena)
```

```{r}
class(survey_egypt)
class(shape_egypt)
class(denom_mena)
```

```{r, eval = F}
shapefile_path <- "data/EGY_adm2.shp"
shape_egypt <- sf::st_read(shapefile_path)
```

```{r, echo =F}
rmarkdown::paged_table(survey_egypt)
```

```{r, echo =F}
rmarkdown::paged_table(shape_egypt)
```

```{r, echo=F}
plot(shape_egypt)
```

```{r, echo =F}
rmarkdown::paged_table(denom_mena)
```

```{r}
denom_egypt <- denom_mena$male_18_sunni[which(denom_mena$country=="Egypt")]
```


```{r, eval = F}

#TODO fix long vectors not supported error--at present below load pre-estimated data list

# prep data
data.list =
data.prep(shape = shape_egypt, survey = survey_egypt,
          shape_large.area_id_name = "ADM1_EN", shape_large.area_id_num = NA,
          shape_small.area_id_name = "ADM2_EN",shape_small.area_id_num = "ADM2_PCODE",
          survey_small.area_id_name = NA, survey_small.area_id_num = "adm2_pcode",
          drop.incomplete.records = T,
          colnames_X = c("coledu","age","married","student","lowstat",
                         "population_density","total_population_2006","christian_2006_pct","university_2006_pct",
                         "agriculture_2006_pct","mursi_vote_2012_pct","sqrt_killed_at_rabaa","unemployment_2013q4_pct",
                         "sqrt_protest_post_Mubarak"),
          interactions_list = list(age2 = "age*age",coledu_lowstat = "coledu*lowstat"),
          scale_X = "1sd",
          colname_y = "case",
          pi = 1000/denom_egypt,
          large_area_shape = T
          )

```

```{r, echo =F}
data(datalist_worm)
```

```{r}
# check that the nb object is fully connected
testconnected(data.list$nb_object)
```

